config/routes.rb
Miaodeguodu::Application.routes.draw do

  root :to => 'home#index'

  resources :items do
    collection do
      post 'rank' => 'items#rank'
    end
  end
  resources :slides
  resources :settings
  resources :codes do
    collection do
      get 'copy_left_tpl' => 'codes#copy_left_tpl'
      get 'copy_right_tpl' => 'codes#copy_right_tpl'
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :cell, :click_url, :image_url, :price, :sort, :short_title
  validates_presence_of :cell, :click_url, :image_url, :sort

  def left_background
    'http://img01.taobaocdn.com/imgextra/i1/112115781/T2J6BjXohNXXXXXXXX_!!112115781.gif'
  end

  def right_background
    'http://img01.taobaocdn.com/imgextra/i1/112115781/T2J6BjXohNXXXXXXXX_!!112115781.gif'
  end

  class << self
    def new_rank(params)
      update_rank(params['image1_urls'], 1)
      update_rank(params['image2_urls'], 2)
      update_rank(params['image3_urls'], 3)
      update_rank(params['image4_urls'], 4)
    end

    private
    def update_rank(image_urls, cell)
      return nil if image_urls.blank?
      sort = 1
      image_urls.split(',').each do |image_url|
        if (item = Item.find_by_image_url(image_url))
          item.update_attributes(cell: cell, sort: sort)
        end
        sort += 1
      end
    end
  end
end

app/models/setting.rb
# encoding: utf-8
class Setting < ActiveRecord::Base
  attr_accessible :key, :value
  validates_presence_of :key, :value
  validates_uniqueness_of :key

  class << self
    def types
      [
          %w(公告图片 1),
          %w(收藏链接图片 2),
          %w(幻灯片下方图片 3),
      ]
    end

    def notice
      (setting = Setting.find_by_key(1)) ? setting.value : ''
    end

    def collect
      (setting = Setting.find_by_key(2)) ? setting.value : ''
    end

    def intro
      (setting = Setting.find_by_key(3)) ? setting.value : ''
    end
  end

  def name
    name =''
    Setting.types.each do |type|
      name = type.first if type.second.to_s == self.key.to_s
    end
    name
  end
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessible :click_url, :image_url, :rank
  validates_presence_of :image_url, :rank

  def self.data_spm_anchor_id
    '11040qTt.1-fxdeC.3-6MqBQb'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def left_menus
    @admin_left_menus = nil
  end

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def index

  end

  def copy_left_tpl
    @items = Item.order('cell ASC, sort ASC')
    render layout: false
  end

  def copy_right_tpl
    @items = Item.order('cell ASC, sort ASC')
    render layout: false
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @items = Item.order('cell ASC, sort ASC')
  end
end

app/controllers/items_controller.rb
# encoding: utf-8
class ItemsController < ApplicationController

  before_filter :left_menus
  before_filter :load_item, only: [:edit, :update, :destroy]

  def index
    @items = Item.order('sort ASC, cell ASC')
  end

  def new
    @item = Item.new
  end

  def update
    if @item.update_attributes(params[:item])
      flash[:success] = '修改成功'
      redirect_to action: :index
    else
      flash[:error] = '修改失败'
      render action: :edit
    end
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      flash[:success] = '添加成功'
      redirect_to action: :new
    else
      flash[:error] = '添加失败'
      render action: :new
    end
  end

  def destroy
    @item.destroy ? flash[:success] = '删除成功' : flash[:error] = '删除失败'
    redirect_to action: :index
  end

  def rank
    Item.new_rank(params)
    render :nothing => true
  end

  def left_menus
      @admin_left_menus = [
          ['宝贝管理', nil],
          ['宝贝列表', items_path, 'items#index'],
          ['添加宝贝', new_item_path, 'items#new']
      ]
  end

  def load_item
    @item = Item.find_by_id(params[:id])
    redirect_to action: :index if @item.nil?
  end
end

app/controllers/settings_controller.rb
# encoding: utf-8
class SettingsController < ApplicationController
  before_filter :load_setting, only: [:edit, :update, :destroy]
  before_filter :left_menus

  def index
    @settings = Setting.all
  end

  def new
    @setting = Setting.new
  end

  def update
    if @setting.update_attributes(params[:setting])
      flash[:success] = '修改成功'
      redirect_to action: :index
    else
      flash[:error] = '修改失败'
      render action: :edit
    end
  end

  def create
    @setting = Setting.new(params[:setting])
    if @setting.save
      flash[:success] = '添加成功'
      redirect_to action: :new
    else
      flash[:error] = '添加失败'
      render action: :new
    end
  end

  def destroy
    @setting.destroy ? flash[:success] = '删除成功' : flash[:error] = '删除失败'
    redirect_to action: :index
  end

  def load_setting
    @setting = Setting.find_by_id(params[:id])
    redirect_to action: :index if @setting.nil?
  end

  def left_menus
      @admin_left_menus = [
          ['其它设置', nil],
          ['配置列表', settings_path, 'settings#index'],
          ['新增配置', new_setting_path, 'settings#new']
      ]
  end
end

app/controllers/slides_controller.rb
# encoding: utf-8
class SlidesController < ApplicationController
  before_filter :load_slide, only: [:edit, :update, :destroy]

  before_filter :left_menus

  def index
    @slides = Slide.order('rank ASC')
  end

  def new
    @slide = Slide.new
  end

  def update
    if @slide.update_attributes(params[:slide])
      flash[:success] = '修改成功'
      redirect_to action: :index
    else
      flash[:error] = '修改失败'
      render action: :edit
    end
  end

  def create
    @slide = Slide.new(params[:slide])
    if @slide.save
      flash[:success] = '添加成功'
      redirect_to action: :new
    else
      flash[:error] = '添加失败'
      render action: :new
    end
  end

  def destroy
    @slide.destroy ? flash[:success] = '删除成功' : flash[:error] = '删除失败'
    redirect_to action: :index
  end

  def load_slide
    @slide = Slide.find_by_id(params[:id])
    redirect_to action: :index if @slide.nil?
  end

  def left_menus
      @admin_left_menus = [
          ['幻灯片管理', nil],
          ['图片列表', slides_path, 'slides#index'],
          ['添加图片', new_slide_path, 'slides#new']
      ]
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  def admin_nav
    navs = [
        ['宝贝管理', items_path],
        ['幻灯片', slides_path],
        ['其它设置', settings_path],
        ['复制代码', codes_path],
        ['预览', root_path]
    ]

    html = ''
    navs.each do |nav|
      html << "<li"
      html << ' class="active"' if nav.second.include?(controller.controller_name)
      html << "><a href='#{nav.second}'>#{nav.first}</a></li>"
    end
    html.html_safe
  end

  def admin_left_menu
    html = ''
    if @admin_left_menus
      @admin_left_menus.each do |menu|
        if menu.second.nil?
          html << "<li class='nav-header'>#{menu.first}</li>"
        else
          active_class = ''
          if menu[2]
            controller_name, action_name = menu[2].split('#')
            if controller_name == controller.controller_name and action_name == controller.action_name
              active_class = ' class="active"'
            end
          end
          html << "<li#{active_class}><a href='#{menu.second}'>#{menu.first}</a></li>"
        end
      end
    end
    html.html_safe
  end
end

app/views/codes/copy_left_tpl.html.erb
<%= render 'shares/left_tpl' %>

app/views/codes/copy_right_tpl.html.erb
<%= render 'shares/right_tpl' %>

app/views/codes/index.html.erb
<%= link_to '获取左侧模板代码', 'javascript:void(0)', class: :btn, onclick: "getTpl('#{copy_left_tpl_codes_path}')" %>

<%= link_to '获取右侧模板代码', 'javascript:void(0)', class: :btn, onclick: "getTpl('#{copy_right_tpl_codes_path}')" %>

<hr>
<div id="preview" style="display: none;">
  <h3>模板代码</h3>

  <div>
    <textarea style="width:600px; height:100px" id="tpl_code"></textarea>
  </div>
  <hr>
  <h3>预览</h3>

  <div id="preview_body"></div>
</div>
<script type="text/javascript">
    function getTpl(url) {
        $.get(url, function (data) {
            var preview_data = data;
            data = data.replace(' class="slide-preview"', '');
            data = data.replace(new RegExp('class="connectedSortable"',"gm"), '');
            data = data.replace('id="sortableId1"', '');
            data = data.replace('id="sortableId2"', '');
            data = data.replace('id="sortableId3"', '');
            data = data.replace('id="sortableId4"', '');
            $('#tpl_code').val(data);
            $('#preview_body').html(preview_data);
            $('#preview').show();

            copyValue(data);
        });
    }

    function copyValue(strValue) {
        if (isIE()) {
            clipboardData.setData("Text", strValue);
            alert("^_^已成功复制");
        }
        else {
            alert("请在文本框内Ctrl+A Ctrl+C 复制");
        }
    }

    function isIE(number) {
        if (typeof(number) != number) {
            return!!document.all;
        }
    }
</script>

app/views/home/index.html.erb
<div class="span10">
  <!-- 左边 -->
  <%= render 'shares/left_tpl', :items => @items %>

  <div style="float:left; width: 10px; height: 500px;">&nbsp;</div>
  <!-- 右边 -->
  <%= render 'shares/right_tpl', {:items => @items, :isPreviewTogether => true} %>

</div>
<div class="span10">
  <hr>
  <div style="text-align: right"><a href="javascript:void(0)" onclick="new_sort()" class="btn btn-primary input-large">排序</a></div>
  <hr>
</div>
<script type="text/javascript">
    $(function () {
        $(".connectedSortable").sortable({
            connectWith:".connectedSortable"
        }).disableSelection();
    });
    function new_sort() {
        var sort1 = [];
        var sort2 = [];
        var sort3 = [];
        var sort4 = [];
        $("#sortableId1").find(".connectedSortable").find('img').each(function () {
            sort1.push($(this).attr('src'));
        });
        $("#sortableId2").find(".connectedSortable").find('img').each(function () {
            sort2.push($(this).attr('src'));
        });
        $("#sortableId3").find(".connectedSortable").find('img').each(function () {
            sort3.push($(this).attr('src'));
        });
        $("#sortableId4").find(".connectedSortable").find('img').each(function () {
            sort4.push($(this).attr('src'));
        });
        $.ajax({
            url:'/items/rank',
            type:'POST',
            data:'image1_urls=' + sort1.join(',') + '&image2_urls=' + sort2.join(',') + '&image3_urls=' + sort3.join(',') + '&image4_urls=' + sort4.join(','),
            success:function () {
                window.location.reload();
            }
        });
    }
</script>

app/views/items/_form.html.erb
<div class="span12">
  <%= simple_form_for(@item, :html => {:class => 'form-horizontal'}) do |f| %>
      <fieldset>
        <legend><%= @item.new_record? ? '添加宝贝' : '编辑宝贝' %></legend>
        <%= f.input :cell, :collection => [%w(第1列 1),%w(第2列 2),%w(第3列 3),%w(第4列 4)] %>
        <%= f.input :sort %>
        <%= f.input :click_url, input_html: {class: 'input-xxlarge'} %>
        <%= f.input :image_url, input_html: {class: 'input-xxlarge'} %>
        <%= f.input :short_title %>
        <%= f.input :price %>
        <div class="form-actions">
          <%= f.submit @item.new_record? ? '添加' : '保存', class: 'btn' %>
        </div>
      </fieldset>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th>图片</th>
    <th>位置</th>
    <th>排序</th>
    <th>短标题</th>
    <th>价钱</th>
    <th>链接地址</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><img src="<%= item.image_url %>" alt="" style="max-width: 30px;"/></td>
        <td><%= item.cell %></td>
        <td><%= item.sort %></td>
        <td><%= item.short_title %></td>
        <td><%= item.price %></td>
        <td><%= item.click_url %></td>
        <td>
          <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_item_path(item) %>
          <%= link_to '<i class="icon-remove"></i>'.html_safe, item_path(item), method: :delete, data:{confirm: '确定要删除？'} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN" xmlns="http://www.w3.org/1999/html">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>喵De国°</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="http://miaodeguodu.taobao.com/">喵De国°</a>

      <div class="nav-collapse">
        <ul class="nav">
          <%= admin_nav %>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <% if @admin_left_menus.nil? %>
        <div class="span12">
          <%= render 'shares/flash_message' %>
          <%= yield %>
        </div>
    <% else %>
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <%= admin_left_menu %>
            </ul>
          </div>
        </div>
        <div class="span10">
          <%= render 'shares/flash_message' %>
          <%= yield %>
        </div>
    <% end %>
  </div>
</div>
</body>
</html>

app/views/settings/_form.html.erb
<div class="span12">
  <%= simple_form_for(@setting, :html => {:class => 'form-horizontal'}) do |f| %>
      <fieldset>
        <legend><%= @setting.new_record? ? '添加' : '编辑' %></legend>
        <%= f.input :key, collection: Setting.types %>
        <%= f.input :value, input_html: {class: 'input-xxlarge'} %>
        <div class="form-actions">
          <%= f.submit @setting.new_record? ? '添加' : '保存', class: 'btn' %>
        </div>
      </fieldset>
  <% end %>
</div>

app/views/settings/edit.html.erb
<%= render 'form' %>

app/views/settings/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>名称</th>
    <th>图片</th>
  </tr>
  </thead>
  <tbody>
  <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.name %></td>
        <td><img src="<%= setting.value %>" alt="" style="max-width: 300px;"/></td>
        <td>
          <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_setting_path(setting) %>
          <%= link_to '<i class="icon-remove"></i>'.html_safe, setting_path(setting), method: :delete, data:{confirm: '确定要删除？'} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/settings/new.html.erb
<%= render 'form' %>

app/views/shares/_flash_message.html.erb
<% if flash %>
    <% flash.each do |k, v| %>
        <div class="alert alert-<%= k %>">
          <input type="button" class="button close" value="×" data-dismiss="alert">

          <p><%= v %></p>
        </div>
    <% end %>
<% end %>

app/views/shares/_left_tpl.html.erb
<div id="sortableId1" style="width:190px; float:left; text-align:center; background:#FFF; line-height: 36px; font-weight: bold; color: #666;">
  <div style="height: 550px; margin-bottom: 20px; overflow: hidden;">
    <div style="height: 350px;">
      <% if Setting.notice != '' %>
      <img src="<%= Setting.notice %>"/>
      <% end %>
      <% if Setting.collect != '' %>
          <a href="http://favorite.taobao.com/popup/add_collection.htm?id=67218909&itemid=67218909&itemtype=0&ownerid=693221d2543d4959880ac12b9e95230c&scjjc=2&_tb_token_=f70305de64459" target="_blank"><img src="<%= Setting.collect %>"/></a>
      <% end %>
    </div>
    <div style="font-size: 12px; font-weight: normal; text-align: left; margin-top: 20px;">
      <h4 style="line-height: 18px;">
        <a href="http://miaodeguodu.taobao.com/search.htm" target="_blank" style="color: #666; font-size: 12px;">查看所有宝贝&gt;&gt;</a>
      </h4>
      <a href="http://miaodeguodu.taobao.com/search.htm?orderType=_hotsell" target="_blank" style="color: #000;">按销量</a>&nbsp;
      <a href="http://miaodeguodu.taobao.com/search.htm?orderType=_newOn" target="_blank" style="color: #000;">按新品</a>&nbsp;
      <a href="http://miaodeguodu.taobao.com/search.htm?orderType=price" target="_blank" style="color: #000;">按价格</a>&nbsp;
      <a href="http://miaodeguodu.taobao.com/search.htm?orderType=_hotkeep" target="_blank" style="color: #000;">按收藏</a>
      <div style="line-height: 30px;"><strong>巴厘岛木猫QQ群:</strong> 246580818</div>
      <h4 style="color: #666; font-size: 12px; line-height: 16px;">在线咨询</h4>
      喵De国&deg;客服1：<a title="点击这里给我发消息" href="http://www.taobao.com/webww/?ver=1&amp;&amp;touid=cntaobaotinylian&amp;siteid=cntaobao&amp;status=2" target="_blank"><img src="http://img.im.alisoft.com/actions/wbtx/wangwang/1/online.gif"></a><br/>
      喵De国&deg;客服2：<a title="点击这里给我发消息" href="http://www.taobao.com/webww/?ver=1&amp;&amp;touid=cntaobaotinylian&amp;siteid=cntaobao&amp;status=2" target="_blank"><img src="http://img.im.alisoft.com/actions/wbtx/wangwang/1/online.gif"></a><br/>
    </div>
  </div>
  <% @items.each do |item| %>
      <% if item.cell == 1 %>
          <div style="height:310px; overflow:hidden;" class="connectedSortable">
            <a href="<%= item.click_url %>" target="_blank"><img src="<%= item.image_url %>" width="100%"></a>
            <br><%= item.short_title.blank? ? '' : "#{item.short_title}&nbsp;".html_safe %><%= item.price.blank? ? '&nbsp;'.html_safe : "RMB: #{item.price}" %>
          </div>
      <% end %>
  <% end %>
</div>

app/views/shares/_right_tpl.html.erb
<div style="width:750px;height:350px;" class="slide-preview">
  <% if Slide.order('rank ASC').first %>
        <% if Slide.order('rank ASC').first.click_url.blank? %>
            <img src="<%= Slide.order('rank ASC').first.image_url %>"/>
        <% else %>
            <a href="<%= Slide.order('rank ASC').first.click_url %>" target="_blank"><img src="<%= Slide.order('rank ASC').first.image_url %>"/></a>
        <% end %>
  <% end %>
</div>
<div style="float:left;width:750px;margin-top:20px;text-align:center;background:#FFF;line-height:36px;font-weight:bold; color:#666;">
  <div style="height: 160px;">
    <img src="<%= Setting.intro %>" width="750px" height="160px">
  </div>
  <div style="height:40px; width:750px;">&nbsp;</div>
  <!-- 第1列 -->
  <div style="width:304px; float:left;" id="sortableId2">
    <% @items.each do |item| %>
        <% if item.cell == 2 %>
            <div style="height:310px;overflow:hidden;">
              <div style="width:52px; float:left;"><img src="<%= item.left_background %>"></div>
              <div style="width:190px; float:left;" class="connectedSortable">
                <a href="<%= item.click_url %>" target="_blank"><img src="<%= item.image_url %>" style="width:100%;"></a>
                <br><%= item.short_title.blank? ? '' : "#{item.short_title}&nbsp;".html_safe %><%= item.price.blank? ? '&nbsp;'.html_safe : "RMB: #{item.price}" %>
              </div>
              <div style="width:52px; float:right;"><img src="<%= item.right_background %>"></div>
            </div>
        <% end %>
    <% end %>
  </div>
  <!-- 第2列 -->
  <div style="width:252px;float:left;" id="sortableId3">
    <% @items.each do |item| %>
        <% if item.cell == 3 %>
            <div style="height:310px;overflow:hidden;">
              <div style="width:190px; float:left;" class="connectedSortable">
                <a href="<%= item.click_url %>" target="_blank"><img src="<%= item.image_url %>" style="width:100%;"></a>
                <br><%= item.short_title.blank? ? '' : "#{item.short_title}&nbsp;".html_safe %><%= item.price.blank? ? '&nbsp;'.html_safe : "RMB: #{item.price}" %>
              </div>
              <div style="width:52px; float:right;"><img src="<%= item.right_background %>"></div>
            </div>
        <% end %>
    <% end %>
  </div>
  <!-- 第3列 -->
  <div style="width:190px; float:left;" id="sortableId4">
    <% @items.each do |item| %>
        <% if item.cell == 4 %>
            <div style="height:310px;overflow:hidden;">
              <div style="width:190px;float:left;" class="connectedSortable">
                <a href="<%= item.click_url %>" target="_blank"><img src="<%= item.image_url %>" style="width:100%;"></a>
                <br><%= item.short_title.blank? ? '' : "#{item.short_title}&nbsp;".html_safe %><%= item.price.blank? ? '&nbsp;'.html_safe : "RMB: #{item.price}" %>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/slides/_form.html.erb
<div class="span12">
  <%= simple_form_for(@slide, :html => {:class => 'form-horizontal'}) do |f| %>
      <fieldset>
        <legend><%= @slide.new_record? ? '添加幻灯图片' : '编辑幻灯图片' %></legend>
        <%= f.input :rank %>
        <%= f.input :image_url, input_html: {class: 'input-xxlarge'} %>
        <%= f.input :click_url, input_html: {class: 'input-xxlarge'} %>
        <div class="form-actions">
          <%= f.submit @slide.new_record? ? '添加' : '保存', class: 'btn' %>
        </div>
      </fieldset>
  <% end %>
</div>

app/views/slides/edit.html.erb
<%= render 'form' %>

app/views/slides/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>排序</th>
    <th>图片</th>
    <th>链接地址</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.rank %></td>
        <td><img src="<%= slide.image_url %>" alt="" style="max-width: 300px;"/></td>
        <td><%= slide.click_url %></td>
        <td>
          <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_slide_path(slide) %>
          <%= link_to '<i class="icon-remove"></i>'.html_safe, slide_path(slide), method: :delete, data:{confirm: '确定要删除？'} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/slides/new.html.erb
<%= render 'form' %>